apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestbook-ingress
spec:
  rules:
  - host: backend.minikube.local
    http:
      paths:
      - backend:
          service:
            name: backend
            port:
              number: 80
        pathType: ImplementationSpecific